### ISSUE TITLE
Can not scroll up/down list view in ScrollableTabView

### ISSUE THREAD

**Issue by nvcken** [brentvatne/react-native-scrollable-tab-view#191]
![scroll-problem](https://cloud.githubusercontent.com/assets/3489866/13545898/c989f092-e2cd-11e5-85e5-cfac82d32128.gif)
Try put [RefreshControlExample](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/RefreshControlExample.js) inside one tab of ScrollableTabView
I can not scroll down to bottom, in list is contain 20 rows item. Even can not pull to refresh
What I wrong?
```xml
<View style={styles.container}>
  <ScrollableTabView initialPage={0} renderTabBar={() => <EvasionTabBar />}>
    <View tabLabel="a" style={styles.tabView}>
        <RefreshControlExample/>
    </View>
  </ScrollableTabView>
</View>;
```

**Comment by nvcken** [comment]
Seem problem came with Navigator component I use ExNavigator
I will try to find out

**Comment by HananeAlSamrout** [comment]
set a height for the scrollView = screenHeight -(TabBarHeight + statusBarHeight)

**Comment by shiqian123** [comment]
Did you solve it？ me too

**Comment by sospedra** [comment]
You're rendering the `ListView` full height. And then trying to scroll it. It's not scrolling because it's not trimmed. Therefore, you can:

A. Make the `ListView` shorter (less height). I guess that your idea would be to fit the screen.
B. Change the `View` parent to `ScrollView` and add the prop `enableScroll={false}` to the `ListView` so you're delegating the scroll responsability to the parent `ScrollView`.

The key concept here is how the scrolling thing works. Quoting the [react-native docs](http://facebook.github.io/react-native/releases/0.40/docs/scrollview.html#scrollview): 
> Keep in mind that ScrollViews must have a bounded height in order to work, since they contain unbounded-height children into a bounded container (via a scroll interaction).
